In [1]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

Wczytanie i konwersja danych

In [2]:
training_set, test_set = mnist.load_data()

In [3]:
X_train, y_train = training_set
X_test, y_test = test_set
print(X_train.shape)

(60000, 28, 28)


In [4]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)
print(X_train.shape)
X_train = X_train.astype(np.float) / 255.0  
X_test = X_test.astype(np.float) / 255.0

(60000, 28, 28, 1)


<ipython-input-4-bbbf7949f131>:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_train = X_train.astype(np.float) / 255.0
<ipython-input-4-bbbf7949f131>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_test = X_test.astype(np.float) / 255.0


Przygotowanie eksperymentu

In [5]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

In [6]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

Uczenie modelu

In [9]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 1s 2ms/step - loss: 0.7433 - accuracy: 0.8161 - val_loss: 0.4070 - val_accuracy: 0.8977
Epoch 2/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3896 - accuracy: 0.8962 - val_loss: 0.3340 - val_accuracy: 0.9097
Epoch 3/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3385 - accuracy: 0.9082 - val_loss: 0.3070 - val_accuracy: 0.9157
Epoch 4/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3147 - accuracy: 0.9126 - val_loss: 0.2943 - val_accuracy: 0.9183
Epoch 5/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3003 - accuracy: 0.9164 - val_loss: 0.2856 - val_accuracy: 0.9210
Epoch 6/30
375/375 [==============================] - 1s 2ms/step - loss: 0.2905 - accuracy: 0.9190 - val_loss: 0.2780 - val_accuracy: 0.9236
Epoch 7/30
375/375 [==============================] - 1s 2ms/step - loss: 0.2832 - accuracy: 0.9211 - val_loss: 0.2753 - val_accuracy: 0.9238
Epoch 

Ocena modelu

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 0s 820us/step
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       980
           1       0.97      0.98      0.97      1135
           2       0.93      0.90      0.91      1032
           3       0.91      0.91      0.91      1010
           4       0.93      0.94      0.93       982
           5       0.89      0.89      0.89       892
           6       0.94      0.95      0.94       958
           7       0.93      0.93      0.93      1028
           8       0.88      0.89      0.89       974
           9       0.93      0.90      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 958    0    1    2    0    7    9    2    1    0]
 [   0 1110    4    3    0    1    3    2   12    0]
 [   3    9  927   17    8    5   14    9   37    3]
 [   3    0   17  920    

Uczenie modeli nieliniowych

MLP

In [27]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [28]:
model.summary()
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X_train, y_train, batch_size=batch_size, epochs=6, validation_split=0.2)

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_6 (Flatten)         (None, 784)               0         
                                                                 
 dense_12 (Dense)            (None, 64)                50240     
                                                                 
 dense_13 (Dense)            (None, 128)               8320      
                                                                 
 dense_14 (Dense)            (None, 10)                1290      
                                                                 
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________
Epoch 1/6
375/375 [==============================] - 1s 3ms/step - loss: 0.4100 - accuracy: 0.8837 - val_loss: 0.2337 - val_accuracy: 0.9337
Epoch 2/6
375/375 [======================

In [29]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 0s 1ms/step
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.95      0.96      1032
           3       0.96      0.97      0.96      1010
           4       0.97      0.97      0.97       982
           5       0.95      0.97      0.96       892
           6       0.97      0.97      0.97       958
           7       0.96      0.96      0.96      1028
           8       0.96      0.96      0.96       974
           9       0.96      0.95      0.95      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

[[ 960    0    0    2    0    5    7    1    2    3]
 [   0 1124    3    0    0    1    3    1    3    0]
 [   7    2  979    9    4    2    5   10   13    1]
 [   0    0    1  975    0 

Sieć Konwolucyjna

In [23]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

In [24]:
model.summary()
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 13, 13, 32)       0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_5 (Flatten)         (None, 1600)              0         
                                                                 
 dropout_1 (Dropout)         (None, 1600)             

In [25]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=3, validation_split=0.2)

Epoch 1/3
375/375 [==============================] - 13s 34ms/step - loss: 0.4005 - accuracy: 0.8785 - val_loss: 0.1065 - val_accuracy: 0.9691
Epoch 2/3
375/375 [==============================] - 13s 35ms/step - loss: 0.1221 - accuracy: 0.9632 - val_loss: 0.0698 - val_accuracy: 0.9797
Epoch 3/3
375/375 [==============================] - 14s 38ms/step - loss: 0.0900 - accuracy: 0.9724 - val_loss: 0.0579 - val_accuracy: 0.9840


In [26]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 4ms/step
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      1.00      0.99      1135
           2       0.97      0.99      0.98      1032
           3       0.98      0.99      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.99      0.98      0.98       892
           6       0.99      0.99      0.99       958
           7       0.98      0.97      0.98      1028
           8       0.98      0.98      0.98       974
           9       0.99      0.97      0.98      1009

    accuracy                           0.98     10000
   macro avg       0.99      0.98      0.98     10000
weighted avg       0.99      0.98      0.98     10000

[[ 972    0    2    0    0    1    1    1    3    0]
 [   0 1131    3    0    0    0    0    0    1    0]
 [   1    4 1022    1    1    0    0    2    1    0]
 [   0    0    3  996    0 